### ISSUE TITLE
Broken in GNOME Web

### ISSUE THREAD

**Issue by atjn** [GoogleChromeLabs/how-fugu-is-my-browser#13]
Hi and thanks for making a cool website :)

I would like to test how well GNOME Web supports Fugu, since it theoretically has the best integration with the GNOME desktop for adding web apps. Unfortunately it doesn't work right now because StorageManager support is missing (and possibly more API's?):

![image](https://github.com/GoogleChromeLabs/how-fugu-is-my-browser/assets/20535393/d69f7f00-d1a2-4bb3-a669-24a59abbd2d6)

**Comment by tomayac** [comment]
I fixed this via https://github.com/tomayac/fugu-api-data/commit/8bbaedcdd19e32f0c429dda9d6c21caa618aaf74 and have updated the app to use the new version in https://github.com/GoogleChromeLabs/how-fugu-is-my-browser/commit/4fd9b9182892f203c74604e8908c54a667bea58c. Does it work for you now?

**Comment by atjn** [comment]
Yes it works now, thank you for a blazing fast fix! Unfortunately only a 13% score :)

**Comment by tomayac** [comment]
Thanks for confirming! Feel free to share the results on the `#HowFuguIsMyBrowser` hashtag.
