### ISSUE TITLE
Push API timeline

### ISSUE THREAD

**Issue by niutech** [GoogleChromeLabs/how-fugu-is-my-browser#19]
The timeline for Push API is linked to the deprecated [PushSubscriptionId](https://chromestatus.com/metrics/feature/timeline/popularity/769) feature, so it doesn't show the real popularity of Push API.

**Comment by tomayac** [comment]
This has rolled out and the curve looks better now:

![Screenshot 2024-08-22 at 12 16 35](https://github.com/user-attachments/assets/7d7aa447-decb-4c7b-ae56-041ab2e0ef10)
